### ISSUE TITLE
[New Upstream Version] New Stable QDirStat Version: V1.9

### ISSUE THREAD

**Issue by shundhammer** [linuxserver/docker-qdirstat#10]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Please update to the just released new upstream version QDirStat-1.9.

  https://github.com/shundhammer/qdirstat/releases/tag/1.9

Release highlights:

- Greatly improved the visual appearance of the treemap 

- Dominant (very large) items are now highlighted in bold font in the 
  tree view

- New "Find" function in the scanned directory tree

- Added support for bookmarks

- New documentation to explain the treemap

- Some small improvements

- Bug fixes

### Reason for change

New upstream version

**Comment by j0nnymoe** [comment]
https://github.com/linuxserver/docker-qdirstat/releases/tag/1.9-ls101 😎

**Comment by aptalca** [comment]
@shundhammer thanks for the heads up and thanks for the new stable release
