### ISSUE TITLE
Unknown QDirStat version number

### ISSUE THREAD

**Issue by shundhammer** [linuxserver/docker-qdirstat#2]
Nice to see more possibilities for users to use QDirStat, now also in this container.

## Problem

But please **clearly** communicate in a prominent place (in particular on the repo's landing page!) what version number of QDirStat users get with this container. I can't see any version number anywhere, and I didn't find any way to find that out.

## Why?

This has become important to me since I came across [this AppImage](https://github.com/shundhammer/qdirstat/issues/168). While I am confident that you will try to distribute the latest official release of QDirStat, please consider that Open Source projects and GitHub repos sometimes get abandoned (this can happen to this container as well), and then the last release will stay around forever. Users might not be aware of that, so it is very well possible that outdated versions of QDirStat in such a container circulate forever, and bug fixes, security updates or new features never reach those users.

This is worse for a container than for a regular Linux distribution because, as you know of course, a container brings its distribution with itself, so users can keep using even a horrendously outdated container for many years.

----------

Kind regards
Stefan Hundhammer
QDirStat Author

**Comment by Roxedus** [comment]
We are grabbing qdirstat from the ubuntu repositories, which is currently at 1.6.1. <https://github.com/linuxserver/docker-qdirstat/blob/master/package_versions.txt#L444>

**Comment by shundhammer** [comment]
@Roxedus: See, and this is exactly what's wrong. V1.6.1 is _horrendously_ outdated. It's from Ubuntu 20.04 which is now almost _two years_ old. QDirStat 1.6.1 was released on 2020-02-13.

Since then, there was

- V1.7 
- V1.7.1
- V1.8
 
There were bug fixes and quite a number of features; see

https://github.com/shundhammer/qdirstat#history

Naturally, users who download and use such a container will expect a recent version; that's the whole point of using a container in the first place.

See also

https://repology.org/project/qdirstat/versions

If you distribute QDirStat, please distribute the recent version, not a two years old one; and please clearly tell the users what version they will get.

**Comment by shundhammer** [comment]
@jlesage, who created the first publicly available QDirStat docker container, keeps his container up-to-date with the latest version; please do the same.

https://github.com/shundhammer/qdirstat#qdirstat-docker-container

**Comment by aptalca** [comment]
His docker hub page shows the latest version he pushed as v1.4.0

**Comment by shundhammer** [comment]
~Yes, I know that the version numbers on that page are also woefully neglected; I'll contact him about that. Thank you.~ But he confirms updating to the latest QDirStat version every time I notify him about it.

- https://github.com/jlesage/docker-qdirstat/issues/5
- https://github.com/jlesage/docker-qdirstat/commit/18962616f0f74d6d71c4bcff45df231083101336
- https://github.com/jlesage/docker-qdirstat/issues/3

**Update:** The QDirStat version number is actually on that page for every release of that docker container.

**Comment by shundhammer** [comment]
See also https://github.com/jlesage/docker-qdirstat/issues/6

**Comment by shundhammer** [comment]
Thank you for providing the latest stable version now!

I just added your container to the QDirStat home page / README.md:
https://github.com/shundhammer/qdirstat#qdirstat-docker-containers

**Comment by aptalca** [comment]
@shundhammer Thanks for maintaining QDirStat.
Your future github releases should automatically trigger a build of our docker image within an hour.
Don't hesitate to ping us with any issues in the future.
