### ISSUE TITLE
Script "10-adduser" takes minutes to execute 

### ISSUE THREAD

**Issue by techie2000** [linuxserver/docker-qdirstat#5]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
App is made available for use 'quickly' (quicker than it does today, and similar to other linuxserver apps)

## Current Behavior
After each container update, its takes upwards of 5mins to be able to use the app as script "10-adduser" 'stalls', with a lot of io and (relatively) high cpu usage before eventually completing without error.

## Steps to Reproduce

1. In Unraid, select the 'Apply Update' option to initiate pull of new image
2. Start the container
3. Wait.....check logs and state via cli

## Environment
**OS:** Slackware 14.2 x86_64 (post 14.2 -current)
**CPU architecture:** x86_64 (AMD Ryzen 9 3950X 16-Core Processor)
**How docker service was installed:** Via the regular/official UnRaid Application gui

## Command used to create docker container (run/create/compose/screenshot)
`/usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker create --name='qdirstat' --net='bridge' --privileged=true -e TZ="Europe/London" -e HOST_OS="Unraid" -e 'PUID'='99' -e 'PGID'='100' -e 'UMASK'='022' -p '3002:3000/tcp' -v '/mnt/':'/data':'rw' -v '/mnt/user/appdata/':'/config':'rw' 'lscr.io/linuxserver/qdirstat' `

## Docker logs

<img width="1122" alt="image" src="https://user-images.githubusercontent.com/38585780/156920518-0a4d3e78-74da-420d-9e50-dd0daf1a1fac.png">

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 01-migrations: executing...
[migrations] started
[migrations] no migrations found
[cont-init.d] 01-migrations: exited 0.
[cont-init.d] 02-tamper-check: executing...
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
_ ()
| | ___ _ __
| | / __| | | / \
| | \__ \ | | | () |
|_| |___/ |_| \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
QDirStat: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=EYJXAVLGNRR5W

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid: 99
User gid: 100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 12-prep_xrdp: executing...
[cont-init.d] 12-prep_xrdp: exited 0.
[cont-init.d] 13-keygen: executing...

Generating 2048 bit rsa key...

ssl_gen_key_xrdp1 ok

saving to rsakeys.ini

Generating a RSA private key
..............+++++
...................................................+++++
writing new private key to '/etc/xrdp/key.pem'
-----
[cont-init.d] 13-keygen: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 1.
[cont-init.d] 50-gid-video: executing...
**** creating video group video8aj3 with id 18 ****
**** adding /dev/dri/renderD128 to video group video8aj3 with id 18 ****
**** permissions for /dev/dri/card0 are good ****
[cont-init.d] 50-gid-video: exited 0.
[cont-init.d] 55-autostart-config: executing...
[cont-init.d] 55-autostart-config: exited 0.
[cont-init.d] 56-openboxcopy: executing...
[cont-init.d] 56-openboxcopy: exited 1.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[guac-init] Auto start not set, application start on login
guacd[533]: INFO: Guacamole proxy daemon (guacd) version 1.1.0 started

guacd[533]: INFO: Listening on host 0.0.0.0, port 4822
Starting guacamole-lite websocket server
listening on *:3000
```

**Comment by thelamer** [comment]
I cannot replicate this, are you mounting some crazy amount of files into `/config` or something odd?

**Comment by techie2000** [comment]
> I cannot replicate this, are you mounting some crazy amount of files into `/config` or something odd?

I looked at it and couldn't see anything unusual in my cli command/setup, but having just revisited it with a fresh pair of eyes I can see a schoolboy error 
`-v '/mnt/user/appdata/':'/config':'rw'` 
instead of 
`-v '/mnt/user/appdata/qdirstat/':'/config':'rw'`
😊 

Modified (corrected) cli and low and behold, expected behaviour observed. 
I'm off to administer self-lashings (and book an eye-test).

Case closed
